config/routes.rb
Rails.application.routes.draw do
  
  
  resources :costs
  resources :incomes
  resources :categories do
    resources :incomes
    resources :costs
    end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :costs, dependent: :destroy
	has_many :incomes, dependent: :destroy
	validates :name, :presence => true
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category
  validates :category_id, :presence => true
  validates :amount, :presence => true
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category
  validates :category_id, :presence => true
  validates :amount, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:category_id, :amount)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:category_id, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><strong>Listing Categories</strong></h1>

<table align="center">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody >
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<strong>Total income=<%=Income.sum(:amount)%><br>
Total cost=<%=Cost.sum(:amount)%></br>
Balance=<%=Income.sum(:amount)-Cost.sum(:amount)%></strong>
<% if((Income.sum(:amount) - Cost.sum(:amount))>500) %><br>
	<script> alert("Hey, Your Balance is greater than 0 : Good to Go"); </script>
	
	<% elsif((Income.sum(:amount) - Cost.sum(:amount))>100) %>
	<script> alert("low balance"); </script>
	
	<% else %>
	<%="alert you are spending alot"%>
<% end %>
<br>
<br>
<%= link_to 'New Category', new_category_path %>
<br><br><br><br><br><br><br><br><br><br><br><br><p><font color="green">Designed by Sushma Singhi Reddy</font></p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<h3>Costs</h3>
<div id="costs">
	<%= @category.costs.each do |cost| %>
	 <%= div_for cost do %>
	 <p>
                
				Debited <%= time_ago_in_words(cost.created_at)%></br>
	 	<strong><%= h(cost.amount) %></strong>
	 </p>
	 <% end %>
	<% end %>
</div>
<h3>Incomes</h3>
<div id="incomes">
	<%= @category.incomes.each do |income| %>
	 <%= div_for income do %>
	 <p>
			
			Credited <%= time_ago_in_words(income.created_at)%></br>
	 	<%= h(income.amount) %>
	 </p>
	 <% end %>
	<% end %>
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Costs</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.category.name %></td>
        <td><%= cost.amount %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @cost.category.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @cost.amount %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incomes</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.category.name %></td>
        <td><%= income.amount %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @income.category.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>